name: Docker Pipeline

on:
  push:
    branches:
      - lab_docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/Mykola-Orlov/Postmodern-technologies:latest
env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}